const Command = require('../../structures/Command');
const axios = require('axios');

class ImageGeneratorCommand extends Command {
    constructor() {
        super({
            name: 'imagine',
            aliases: ['img', 'ai-img'],
            description: 'Generate AI images',
            category: 'tools',
            usage: '.imagine <prompt>'
        });
    }

    async execute(message, args) {
        if (!args.length) return message.reply('Please provide a prompt for the image!');

        const prompt = args.join(' ');
        await message.reply('⌛ *Generating your image...*');

        try {
            // Using free Lexica API
            const response = await axios.get(`https://lexica.art/api/v1/search?q=${encodeURIComponent(prompt)}`);
            const images = response.data.images;
            
            if (images && images.length > 0) {
                const randomImage = images[Math.floor(Math.random() * images.length)];
                
                await message.client.sendMessage(message.key.remoteJid, {
                    image: { url: randomImage.src },
                    caption: `🎨 *AI Generated Image*\n\n` +
                            `🔍 Prompt: ${prompt}\n` +
                            `✨ Generated by Dineth MD`
                });
            } else {
                message.reply('❌ No images found for your prompt. Try something else!');
            }
        } catch (error) {
            console.error('Image generation error:', error);
            message.reply('❌ Failed to generate image. Please try again.');
        }
    }
}

module.exports = ImageGeneratorCommand; 