const Command = require('../../structures/Command');
const { downloadMediaMessage } = require('@adiwajshing/baileys');
const sharp = require('sharp');
const path = require('path');
const fs = require('fs').promises;

class MemeGeneratorCommand extends Command {
    constructor() {
        super({
            name: 'meme',
            aliases: ['makememe', 'memegen'],
            description: 'Create custom memes',
            category: 'tools',
            usage: '.meme <top text> | <bottom text>'
        });
    }

    async execute(message, args) {
        if (!message.quoted || !args.length) {
            return message.reply(`╭─❒ 『 MEME GENERATOR 』 ❒
│
├─❒ 🎨 *Usage:*
│ .meme <top> | <bottom>
│ (Reply to an image)
│
├─❒ 📝 *Example:*
│ .meme Me | Also Me
│
├─❒ 🔍 *Features:*
│ • Custom text
│ • Auto text sizing
│ • Impact font
│
├─❒ ✨ *Powered by:* Dineth MD
│
╰──────────────────❒`);
        }

        const [topText, bottomText] = args.join(' ').split('|').map(text => text.trim());

        try {
            const buffer = await downloadMediaMessage(message.quoted, 'buffer');
            const outputPath = path.join(__dirname, `../../../temp/${Date.now()}.jpg`);

            // Add text to image using sharp
            await sharp(buffer)
                .resize(800, 800, { fit: 'inside' })
                .composite([
                    {
                        input: await this.createTextOverlay(topText, 'top'),
                        top: 10,
                        left: 0
                    },
                    {
                        input: await this.createTextOverlay(bottomText, 'bottom'),
                        bottom: 10,
                        left: 0
                    }
                ])
                .toFile(outputPath);

            await message.client.sendMessage(message.key.remoteJid, {
                image: { url: outputPath },
                caption: '✨ Generated by Dineth MD'
            });

            await fs.unlink(outputPath);

        } catch (error) {
            console.error('Meme generation error:', error);
            message.reply('❌ Failed to generate meme.');
        }
    }

    async createTextOverlay(text, position) {
        // Implementation for creating text overlay with Impact font
        // This would use sharp's SVG text rendering capabilities
        return Buffer.from(`
            <svg width="800" height="100">
                <style>
                    .text { 
                        font-family: Impact; 
                        font-size: 48px; 
                        fill: white; 
                        stroke: black;
                        stroke-width: 2px;
                        text-anchor: middle;
                    }
                </style>
                <text x="400" y="50" class="text">${text}</text>
            </svg>
        `);
    }
}

module.exports = MemeGeneratorCommand; 