const Command = require('../../structures/Command');
const gtts = require('node-gtts');
const path = require('path');
const fs = require('fs').promises;

class TextToSpeechCommand extends Command {
    constructor() {
        super({
            name: 'tts',
            aliases: ['say', 'speak'],
            description: 'Convert text to speech',
            category: 'tools',
            usage: '.tts <lang> <text>'
        });
    }

    async execute(message, args) {
        if (args.length < 2) {
            return message.reply(`╭─❒ 『 TEXT TO SPEECH 』 ❒
│
├─❒ 🗣️ *Usage:*
│ .tts <lang> <text>
│
├─❒ 📝 *Example:*
│ .tts en Hello World
│
├─❒ 🌐 *Languages:*
│ • en - English
│ • si - Sinhala
│ • ta - Tamil
│ • hi - Hindi
│ • ja - Japanese
│
├─❒ ✨ *Powered by:* Dineth MD
│
╰──────────────────❒`);
        }

        const lang = args[0];
        const text = args.slice(1).join(' ');
        const outputPath = path.join(__dirname, `../../../temp/${Date.now()}.mp3`);

        try {
            await message.reply('🎯 *Generating audio...*');
            
            await new Promise((resolve, reject) => {
                const tts = gtts(lang);
                tts.save(outputPath, text, (err) => {
                    if (err) reject(err);
                    else resolve();
                });
            });

            await message.client.sendMessage(message.key.remoteJid, {
                audio: { url: outputPath },
                mimetype: 'audio/mp4',
                ptt: true,
                caption: '✨ Generated by Dineth MD'
            });

            await fs.unlink(outputPath);

        } catch (error) {
            console.error('TTS error:', error);
            message.reply('❌ Failed to generate speech.');
        }
    }
}

module.exports = TextToSpeechCommand; 