const Command = require('../../structures/Command');
const axios = require('axios');

class AnimeImageCommand extends Command {
    constructor() {
        super({
            name: 'animepic',
            aliases: ['waifu', 'anime'],
            description: 'Get random anime images',
            category: 'anime',
            usage: '.animepic <category>'
        });

        this.categories = [
            'waifu', 'neko', 'shinobu', 'megumin', 'bully',
            'cuddle', 'cry', 'hug', 'awoo', 'kiss', 'pat',
            'smug', 'bonk', 'yeet', 'blush', 'smile'
        ];
    }

    async execute(message, args) {
        const category = args[0]?.toLowerCase() || 'waifu';
        
        if (!this.categories.includes(category)) {
            return message.reply(`Invalid category! Available categories:\n${this.categories.join(', ')}`);
        }

        try {
            // Using waifu.pics API (free, no key needed)
            const response = await axios.get(`https://api.waifu.pics/sfw/${category}`);
            
            await message.client.sendMessage(message.key.remoteJid, {
                image: { url: response.data.url },
                caption: `🌸 *Category:* ${category}\n✨ Generated by Dineth MD`
            });
        } catch (error) {
            console.error('Anime image error:', error);
            message.reply('❌ Failed to get anime image. Please try again.');
        }
    }
}

module.exports = AnimeImageCommand; 